# Generated by Django 3.1.1 on 2021-02-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=100, null=True)),
                ('Job_type', models.CharField(max_length=100, null=True)),
                ('Level', models.TextField()),
                ('Job_description', models.DateTimeField(auto_now=True, null=True)),
                ('Application', models.CharField(max_length=100, null=True)),
                ('Application_target', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
