# Generated by Django 3.1.1 on 2021-02-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Company_logo', models.CharField(max_length=100, null=True)),
                ('Website', models.TextField()),
                ('Description', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job_post',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
