# Generated by Django 3.1.1 on 2021-02-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210201_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
