# Generated by Django 3.1.1 on 2021-02-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210201_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
        migrations.AlterField(
            model_name='company',
            name='Company_logo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
