# Generated by Django 3.1.1 on 2021-02-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20210201_0422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
