# Generated by Django 3.1.1 on 2021-02-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Job_description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
