# Generated by Django 3.1.1 on 2021-02-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.company'),
        ),
    ]
