# Generated by Django 3.1.1 on 2021-02-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20210202_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='company',
        ),
    ]
