# Generated by Django 3.1.1 on 2021-02-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_job_post_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Company_logo',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
