# Generated by Django 3.1.1 on 2021-02-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0016_auto_20210202_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Company_logo', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('website', models.CharField(max_length=100, null=True)),
                ('Job_description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
