# Generated by Django 3.1.1 on 2021-02-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_auto_20210202_0309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photo',
        ),
    ]
