# Generated by Django 3.1.1 on 2021-02-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Describe_yourself', models.CharField(max_length=200, null=True)),
                ('Location', models.CharField(max_length=200, null=True)),
                ('Job_preferences', models.CharField(choices=[('I am looking for a Vue.js job', 'I am looking for a Vue.js job'), ('Open, but not looking', 'Open, but not looking'), ('Not looking for a job', 'Not looking for a job')], max_length=100, null=True)),
            ],
        ),
    ]
