# Generated by Django 3.1.1 on 2021-02-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='Level_of_seniority',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Junior', 'Junior'), ('Mid level', 'Mid level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], max_length=100, null=True),
        ),
    ]
