# Generated by Django 3.1.1 on 2021-02-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_developer_level_of_seniority'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='Job',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('intenship', 'intenship'), ('part-time', 'part-time'), ('Freelance', 'Freelance'), ('Temporary', 'Temporary')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='Privacy',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='Skill_Set',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='laguage',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='Describe_yourself',
            field=models.TextField(null=True),
        ),
    ]
