# Generated by Django 3.1.1 on 2021-02-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_auto_20210202_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='CV',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
