# Generated by Django 3.1.1 on 2021-02-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_developer_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=100, null=True)),
                ('Company_logo', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('Company_Describe', models.TextField(null=True)),
                ('website', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
