# Generated by Django 3.1.1 on 2021-02-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_company_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detail',
            name='Company_logo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
