# Generated by Django 3.1.1 on 2021-02-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_auto_20210202_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='CV',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
