# Generated by Django 3.1.4 on 2021-02-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_company_creat_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='photo',
        ),
        migrations.AddField(
            model_name='developer',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
