# Generated by Django 3.1.1 on 2021-02-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_auto_20210205_0144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
