# Generated by Django 3.1.1 on 2021-02-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_developer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='user',
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='How_to_apply',
            field=models.TextField(default='true'),
            preserve_default=False,
        ),
    ]
