# Generated by Django 3.1.1 on 2021-02-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(blank=True, default='true', max_length=100),
            preserve_default=False,
        ),
    ]
