# Generated by Django 3.1.1 on 2021-02-06 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_auto_20210206_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_detail',
            name='Company_name',
            field=models.CharField(blank=True, default=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=100),
        ),
    ]
