# Generated by Django 3.1.1 on 2021-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_auto_20210206_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_detail',
            name='Company_name',
            field=models.CharField(max_length=100),
        ),
    ]
