# Generated by Django 3.1.1 on 2021-02-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_auto_20210206_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_detail',
            name='Company_name',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
