# Generated by Django 3.1.1 on 2021-02-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_auto_20210206_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
