# Generated by Django 3.1.1 on 2021-02-08 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0054_company_detail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_detail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='test_detail',
            name='developer',
        ),
        migrations.AddField(
            model_name='test_detail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
