# Generated by Django 3.1.1 on 2021-02-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0055_auto_20210208_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_detail',
            name='Company_logo',
        ),
    ]
