# Generated by Django 3.1.1 on 2021-02-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0056_remove_test_detail_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_detail',
            name='Company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
