# Generated by Django 3.1.1 on 2021-02-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0057_auto_20210208_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_detail',
            name='developer',
            field=models.TextField(null=True),
        ),
    ]
