# Generated by Django 3.1.1 on 2021-02-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0061_auto_20210208_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
