# Generated by Django 3.1.1 on 2021-02-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0062_auto_20210208_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_detail',
            name='short_des',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
