# Generated by Django 3.1.1 on 2021-02-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0063_company_detail_short_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='email_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
