# Generated by Django 3.1.1 on 2021-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0065_auto_20210209_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_detail',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
