# Generated by Django 3.1.1 on 2021-02-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0066_company_detail_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_detail',
            old_name='email',
            new_name='email_address',
        ),
    ]
