# Generated by Django 3.1.1 on 2021-02-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0067_auto_20210209_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detail',
            name='Company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
