# Generated by Django 3.1.1 on 2021-02-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0068_auto_20210209_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detail',
            name='Company_logo',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='images/'),
        ),
    ]
