# Generated by Django 3.1.1 on 2021-02-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0071_auto_20210209_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
