# Generated by Django 3.1.1 on 2021-02-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0072_developer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='profile_pic',
            field=models.FileField(blank=True, default='profile1.png', null=True, upload_to='images/'),
        ),
    ]
