# Generated by Django 3.1.1 on 2021-02-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0073_auto_20210211_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_detail',
            name='short_Job_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
