# Generated by Django 3.1.1 on 2021-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0074_company_detail_short_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detail',
            name='Company_logo',
            field=models.ImageField(default='profile1.png', null=True, upload_to='images/'),
        ),
    ]
