# Generated by Django 3.1.1 on 2021-02-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0078_auto_20210216_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
