# Generated by Django 3.1.1 on 2021-03-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0082_company_detail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detail',
            name='Application_target',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='Company_Describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='Company_logo',
            field=models.ImageField(blank=True, default='images/profile1.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='Company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='How_to_apply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='Job',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('intenship', 'intenship'), ('part-time', 'part-time'), ('Freelance', 'Freelance'), ('Temporary', 'Temporary')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='Job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='Job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='Level_of_seniority',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Junior', 'Junior'), ('Mid level', 'Mid level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='Location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='short_Job_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jobs.Tag'),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
